"""
Retell AI Webhook Event Models
================================
Pydantic models for all Retell AI webhook event types.

Retell sends webhooks for:
  - call_started
  - call_ended
  - call_analyzed   (post-call analysis — transcript, summary, sentiment)

Docs: https://docs.retellai.com/api-references/webhooks
"""

from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────────────

class RetellCallStatus(str, Enum):
    REGISTERED   = "registered"
    ONGOING      = "ongoing"
    ENDED        = "ended"
    ERROR        = "error"


class RetellDisconnectionReason(str, Enum):
    USER_HANGUP            = "user_hangup"
    AGENT_HANGUP           = "agent_hangup"
    CALL_TRANSFER          = "call_transfer"
    VOICEMAIL_REACHED      = "voicemail_reached"
    INACTIVITY             = "inactivity"
    MACHINE_DETECTED       = "machine_detected"
    MAX_DURATION_REACHED   = "max_duration_reached"
    CONCURRENCY_LIMIT      = "concurrency_limit_reached"
    NO_VALID_PAYMENT       = "no_valid_payment"
    ERROR_INBOUND_WEBHOOK  = "error_inbound_webhook"
    DIAL_BUSY              = "dial_busy"
    DIAL_FAILED            = "dial_failed"
    DIAL_NO_ANSWER         = "dial_no_answer"


class RetellSentiment(str, Enum):
    POSITIVE = "Positive"
    NEGATIVE = "Negative"
    NEUTRAL  = "Neutral"
    UNKNOWN  = "Unknown"


# ── Transcript Models ────────────────────────────────────────────────────────

class RetellTranscriptWord(BaseModel):
    word: str
    start: float  # seconds from call start
    end: float


class RetellTranscriptUtterance(BaseModel):
    role: str  # "agent" | "user"
    content: str
    words: list[RetellTranscriptWord] = []


# ── Call Object ───────────────────────────────────────────────────────────────

class RetellCallObject(BaseModel):
    call_id: str
    agent_id: str
    call_status: RetellCallStatus
    call_type: str  # "phone_call" | "web_call"

    # Phone call specific
    from_number: Optional[str] = None
    to_number: Optional[str] = None

    # Timing
    start_timestamp: Optional[int] = None       # Unix ms
    end_timestamp: Optional[int] = None         # Unix ms
    duration_ms: Optional[int] = None

    # Content
    transcript: Optional[str] = None
    transcript_object: Optional[list[RetellTranscriptUtterance]] = None
    transcript_with_tool_calls: Optional[list[dict]] = None

    # Analysis (populated after call ends + analysis runs)
    call_analysis: Optional[dict] = None

    # Disconnection
    disconnection_reason: Optional[RetellDisconnectionReason] = None

    # Metadata we injected when creating the call
    metadata: Optional[dict] = None
    retell_llm_dynamic_variables: Optional[dict] = None

    # Recording
    recording_url: Optional[str] = None

    # Custom data from LLM
    call_cost: Optional[float] = None


# ── Webhook Event Models ──────────────────────────────────────────────────────

class RetellWebhookEvent(BaseModel):
    """Base model for all Retell webhook events."""
    event: str                          # "call_started" | "call_ended" | "call_analyzed"
    call: RetellCallObject


class RetellCallStartedEvent(RetellWebhookEvent):
    """Fired when the call is connected and audio begins."""
    event: str = "call_started"


class RetellCallEndedEvent(RetellWebhookEvent):
    """
    Fired when the call disconnects.
    Transcript is available at this point.
    """
    event: str = "call_ended"


class RetellCallAnalyzedEvent(RetellWebhookEvent):
    """
    Fired after Retell's post-call analysis completes (~seconds after call ends).
    Contains: call_summary, user_sentiment, agent_sentiment, custom_analysis_data.
    This is the primary trigger for Agent B evaluation.
    """
    event: str = "call_analyzed"


# ── Call Analysis Models ──────────────────────────────────────────────────────

class RetellCallAnalysis(BaseModel):
    """
    Post-call analysis generated by Retell AI.
    Populated in call.call_analysis after 'call_analyzed' event.
    """
    call_summary: Optional[str] = None
    user_sentiment: Optional[RetellSentiment] = None
    agent_sentiment: Optional[RetellSentiment] = None
    call_successful: Optional[bool] = None

    # Custom data extracted during call (from Retell LLM tool calls)
    custom_analysis_data: Optional[dict[str, Any]] = None

    # In_voicemail detection
    in_voicemail: Optional[bool] = None
